### ISSUE TITLE
Do you compare with druid?

### ISSUE THREAD

**Issue by p0mp0k0** [brettwooldridge/HikariCP-benchmark#6] opened 2016-08-17 15:26 UTC
Do you compare with druid,? It's a connection pool created by alibaba develop team, and it was called the best connection pool in chinese, so I want to know whose performance is better. 
The project at git is: https://github.com/alibaba/druid
Thanks.

**Comment by brettwooldridge** [comment] 2016-08-17 23:45
Duplicate of [HikariCP#232](https://github.com/brettwooldridge/HikariCP/issues/232)

**Closed by brettwooldridge** 2016-08-17 23:45 UTC
